<?php
	session_start();
	include('conn.php');

	$charges = $_SESSION['account_name'];
	$start_date = $_SESSION['start_date'];
	$end_date = $_SESSION['end_date'];

	$sql = "SELECT tbl_voucher_details.*, tbl_voucher.* from tbl_voucher_details join tbl_voucher on tbl_voucher.voucher_id=tbl_voucher_details.voucher_id";

	if($charges!="" && $charges!="All"){
		$sql .= ' where voucher_description="'.$charges.'"';
	}
						
	if(!$start_date==""){
		if(!$end_date==""){
			$sql .= ' and tbl_voucher.voucher_date between "'.$start_date.'" and "'.$end_date.'"';
		} else {
			$sql .= ' and tbl_voucher.voucher_date="'.$start_date.'"';
		}
	}
					
	$sql .= ' order by tbl_voucher_details.voucher_id desc';
	$query = mysqli_query($connection,$sql);

	$getID = mysqli_fetch_assoc(mysqli_query($connection, "SELECT * FROM login WHERE user = '".$_SESSION['user']."'"));
    $userfullname = $getID['fullname'];

	$date_today = time();
	$idStamp = date("mdhisY", $date_today);
?>
<link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../css/style.css">

<div class="my-spacer"></div>
<div class="my-spacer"></div>

<div class="container">
	<div class="row">
		<h1>CASH DISBURSEMENT</h1>
	</div>
	<div class="row">
		as of <?php echo date("M d, Y",time());?>
	</div>
	<div class="row">
		Generated by: <?php echo $userfullname;?>
	</div>
	<div class="row">
		Document #: <?php echo $idStamp;?>
	</div>
</div>

<div class="my-spacer"></div>

<div class="container">
	<div class="row">
		<div class="col-10">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th class="text-center">Voucher #</th>
						<th class="text-center">Description</th>
						<th class="text-center">Amount</th>
						<th class="text-center">Date</th>
					</tr>
				</thead>
				<tbody>
					<?php
					
					while($row=mysqli_fetch_assoc($query)){
						echo '<tr>';
						echo '<td>'.$row['voucher_id'].'</td>';
						echo '<td>'.$row['voucher_description'].'</td>';
						echo '<td class="text-right">'.number_format($row['voucher_amount'],'2','.',',').'</td>';
						echo '<td class="text-center">'.$row['voucher_date'].'</td>';
						echo '</tr>';
					}
					?>
				</tbody>
				<tfoot>
					
				</tfoot>
			</table>
		</div>
	</div>
</div>
